# Generated by Django 5.1.1 on 2024-10-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '002_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Preferences'},
        ),
    ]
